"""Create all table

Revision ID: dfa63b65738e
Revises: 
Create Date: 2024-06-11 16:28:32.115745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa63b65738e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_of_body', sa.String(), nullable=True),
    sa.Column('exercise1', sa.String(), nullable=True),
    sa.Column('exercise2', sa.String(), nullable=True),
    sa.Column('exercise3', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bench_press', sa.String(), nullable=True),
    sa.Column('raising_hands', sa.String(), nullable=True),
    sa.Column('holding_hands', sa.String(), nullable=True),
    sa.Column('bench_of_Scott', sa.String(), nullable=True),
    sa.Column('hammer', sa.String(), nullable=True),
    sa.Column('pull_ups', sa.String(), nullable=True),
    sa.Column('bar_pull_below', sa.String(), nullable=True),
    sa.Column('bar_pull_overhead', sa.String(), nullable=True),
    sa.Column('block_pull_below', sa.String(), nullable=True),
    sa.Column('curring_dumbbells_head', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complect1', sa.Integer(), nullable=True),
    sa.Column('complect2', sa.Integer(), nullable=True),
    sa.Column('complect3', sa.Integer(), nullable=True),
    sa.Column('day1', sa.String(), nullable=True),
    sa.Column('day2', sa.String(), nullable=True),
    sa.Column('day3', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['complect1'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['complect2'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['complect3'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('program', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['program'], ['program.id'], ),
    sa.ForeignKeyConstraint(['result'], ['result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    op.drop_table('program')
    op.drop_table('result')
    op.drop_table('exercise')
    # ### end Alembic commands ###
